name: restaurant_reservations
description: A new Flutter project for restaurant reservations.

# Version del proyecto
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_storage: ^11.6.5
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.0.0

  # Otras dependencias adicionales que utilices
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/


  # Si tienes más imágenes, las agregas aquí
  # Ejemplo:
  # - assets/images/otra_imagen.jpg
