// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTjGrlshigtde4D80QAb7VFPW_a4ciWM',
    appId: '1:83725086983:web:1860ced8a9be8227cbd5a2',
    messagingSenderId: '83725086983',
    projectId: 'proyecto-personal-alejandro',
    authDomain: 'proyecto-personal-alejandro.firebaseapp.com',
    storageBucket: 'proyecto-personal-alejandro.firebasestorage.app',
    measurementId: 'G-GLEB9RG4FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMbB3B_3uiicTzrYhB63M2jGGjPhK3X9Y',
    appId: '1:83725086983:android:75df6fec1d866a13cbd5a2',
    messagingSenderId: '83725086983',
    projectId: 'proyecto-personal-alejandro',
    storageBucket: 'proyecto-personal-alejandro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9B59A6a40TSvIiA8jaWSPAm_0URyOZ0',
    appId: '1:83725086983:ios:01e1f690c3a39959cbd5a2',
    messagingSenderId: '83725086983',
    projectId: 'proyecto-personal-alejandro',
    storageBucket: 'proyecto-personal-alejandro.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReservations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG9B59A6a40TSvIiA8jaWSPAm_0URyOZ0',
    appId: '1:83725086983:ios:01e1f690c3a39959cbd5a2',
    messagingSenderId: '83725086983',
    projectId: 'proyecto-personal-alejandro',
    storageBucket: 'proyecto-personal-alejandro.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReservations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiTjGrlshigtde4D80QAb7VFPW_a4ciWM',
    appId: '1:83725086983:web:9d3b209a91034a09cbd5a2',
    messagingSenderId: '83725086983',
    projectId: 'proyecto-personal-alejandro',
    authDomain: 'proyecto-personal-alejandro.firebaseapp.com',
    storageBucket: 'proyecto-personal-alejandro.firebasestorage.app',
    measurementId: 'G-2VHZXNBXH7',
  );
}
